#!/usr/bin/zsh

bindkey -e
setopt NO_BEEP

# Changing directory options
setopt CD_SILENT
setopt CHASE_LINKS

# Completion options
setopt ALWAYS_TO_END
setopt NO_AUTO_MENU

# History options
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# I/O options
setopt INTERACTIVE_COMMENTS
setopt NO_FLOW_CONTROL

# Job control options
setopt NOTIFY

# Key bindings
bindkey '^[[1;5C' forward-word   # Ctrl + Right
bindkey '^[[1;5D' backward-word  # Ctrl + Left
bindkey '^[[H' beginning-of-line # Home
bindkey '^[[F' end-of-line       # End
bindkey '^[[3;5~' kill-word      # Ctrl + Delete
bindkey '^H' backward-kill-word  # Ctrl + Backspace
bindkey '^[[3~' delete-char      # Delete
bindkey '^[[5~' forward-word # PageUp
bindkey '^[[6~' backward-word # PageDown

export LS_COLORS="$(vivid generate gruvbox-dark-soft)"
source $XDG_CONFIG_HOME/aliases.sh

autoload -Uz compinit && compinit
autoload -U select-word-style && select-word-style bash

source <(fzf --zsh)
if [[ ! -e $ZDOTDIR/fzf-tab ]]; then
  git clone https://github.com/Aloxaf/fzf-tab.git $ZDOTDIR/fzf-tab
fi
source $ZDOTDIR/fzf-tab/fzf-tab.plugin.zsh
enable-fzf-tab

if [[ ! -e $ZDOTDIR/zsh-syntax-highlighting ]]; then
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $ZDOTDIR/zsh-syntax-highlighting
fi
source $ZDOTDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' menu no
# zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept

eval "$(oh-my-posh init zsh --config $XDG_CONFIG_HOME/ohmyposh/zen.toml)"
eval "$(direnv hook zsh)"
eval "$(zoxide init zsh --cmd cd)"
