colorscheme gruvbox-dark

set-option -add global autoinfo normal
set-option global ui_options terminal_assistant=none
set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 5,3

add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ wrap -word -indent

# Do not use alphas for navigation
# map global normal h ? # TODO: Find use for this key
# map global normal j ? # TODO: Find use for this key
# map global normal k ? # TODO: Find use for this key
map global normal l x

map -docstring "line begin" global goto <left> h
# map global goto <up> j
# map global goto <up> k
map -docstring "line end" global goto <right> l


map -docstring "yank the selection into the clipboard" global user y "<a-|> wl-copy<ret>"
map -docstring "paste the clipboard" global user p "<a-!> wl-paste<ret>"

add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching

# set cursor to underline
hook global InsertIdle .* %{
  set-face window PrimaryCursor default,default+u
  set-face window PrimaryCursorEol default,default+u
  set-face window SecondaryCursor default,default+u
  set-face window SecondaryCursorEol default,default+u
  set-face window PrimarySelection default,default
  set-face window SecondarySelection default,default
}

# set cursor to default
hook global NormalIdle .* %{
  unset-face window PrimaryCursor
  unset-face window PrimaryCursorEol
  unset-face window SecondaryCursor
  unset-face window SecondaryCursorEol
  unset-face window PrimarySelection
  unset-face window SecondarySelection
}

