[window]
decorations = "None"
dynamic_title = true
padding = {x = 4, y = 4}

[scrolling]
history = 10000

[font]
size = 16.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[cursor]
style = "Block"

[general]
import = [
	"~/.config/alacritty/gruvbox_dark.toml"
]

[keyboard]
bindings = [
  {key = "PageUp", mods = "Control", action = "ScrollLineUp"},
  {key = "PageDown", mods = "Control", action = "ScrollLineDown"},
]
