[window]
decorations = "None"
dynamic_title = true
padding = {x = 4, y = 4}

[scrolling]
history = 10000

[font]
size = 16.0

[font.normal]
family = "Iosevka Term"

[font.bold]
family = "Iosevka Term"

[font.bold_italic]
family = "Iosevka Term"

[font.italic]
family = "Iosevka Term"

[cursor]
style = "Block"

[general]
import = [
	"~/.config/alacritty/gruvbox_material_dark.toml"
]

[keyboard]
bindings = [
  {key = "PageUp", mods = "Control", action = "ScrollLineUp"},
  {key = "PageDown", mods = "Control", action = "ScrollLineDown"},
]
