# Colors (Gruvbox Material Soft Dark)

# Default colors
[colors.primary]
background = '#32302f'
foreground = '#e2cca9'

# Normal colors
[colors.normal]
black   = '#252423'
red     = '#f2594b'
green   = '#b0b846'
yellow  = '#e9b143'
blue    = '#80aa9e'
magenta = '#d3869b'
cyan    = '#8bba7f'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
